version: '2.12.1'
services:
  converter:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
  convertersql:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=M@ps5250864SQL
      - MYSQL_DATABASE=converter_db

networks:
  default:
    name: converter-network-project